export const blogPosts = [
    {
        id: 1,
        title: 'Getting Started with Hosting',
        description: 'Learn the basics of hosting and how to set up your first website.',
        image: '/sample_blog_image.png',
        link: '/blog/getting-started-with-hosting',
        author: 'John Doe',
        readTime: '5',
        date: '01/01/2023',
        tags: ['hosting', 'website', 'beginner'],
    },
    {
        id: 2,
        title: 'Optimising Your Hosting Performance',
        description: 'Tips and tricks to improve your hosting speed and overall performance.',
        image: '/sample_blog_image.png',
        link: '/blog/optimising-hosting-performance',
        author: 'John Doe',
        readTime: '4',
        date: '01/02/2023',
        tags: ['performance', 'optimisation', 'speed'],
    },
    {
        id: 3,
        title: 'The Importance of Hosting Security',
        description: 'Understanding the key aspects of hosting security and how to protect your online presence.',
        image: '/sample_blog_image.png',
        link: '/blog/importance-of-hosting-security',
        author: 'John Doe',
        readTime: '6',
        date: '01/03/2023',
        tags: ['security', 'protection', 'online'],
    },
    {
        id: 4,
        title: 'Choosing the Right Hosting Plan',
        description: 'A guide to selecting the best hosting plan for your needs.',
        image: '/sample_blog_image.png',
        link: '/blog/choosing-right-hosting-plan',
        author: 'John Doe',
        readTime: '5',
        date: '01/04/2023',
        tags: ['hosting', 'guide', 'selection'],
    },
    {
        id: 5,
        title: 'Common Hosting Mistakes to Avoid',
        description: 'Learn about the most common pitfalls in hosting and how to avoid them.',
        image: '/sample_blog_image.png',
        link: '/blog/common-hosting-mistakes',
        author: 'John Doe',
        readTime: '3',
        date: '01/05/2023',
        tags: ['mistakes', 'hosting', 'advice'],
    },
    {
        id: 6,
        title: 'How to Migrate Your Website to a New Host',
        description: 'Step-by-step instructions for migrating your website seamlessly.',
        image: '/sample_blog_image.png',
        link: '/blog/migrate-website-new-host',
        author: 'John Doe',
        readTime: '7',
        date: '01/06/2023',
        tags: ['migration', 'website', 'instructions'],
    },
];