export const knowledgebaseArticles = [
    {
        id: 1,
        title: 'How to Set Up Your Hosting Account',
        description: 'A step-by-step guide to setting up your hosting account and getting started with your website.',
        link: '/knowledgebase/how-to-set-up-your-hosting-account',
        author: 'John Doe',
        readTime: '5',
        date: '2023-05-01',
        category: 'Getting Started',
        tags: ['hosting', 'setup', 'beginner'],
    },
    {
        id: 2,
        title: 'Troubleshooting Common Hosting Issues',
        description: 'Learn how to resolve common hosting problems and keep your website running smoothly.',
        link: '/knowledgebase/troubleshooting-common-hosting-issues',
        author: 'Jane Smith',
        readTime: '8',
        date: '2023-05-15',
        category: 'Troubleshooting',
        tags: ['hosting', 'troubleshooting', 'maintenance'],
    },
    {
        id: 3,
        title: 'Understanding Domain Names',
        description: 'A comprehensive guide to domain names and how to choose the right one for your website.',
        link: '/knowledgebase/understanding-domain-names',
        author: 'Alice Johnson',
        readTime: '6',
        date: '2023-06-01',
        category: 'Getting Started',
        tags: ['domain', 'website', 'beginner'],
    },
    {
        id: 4,
        title: 'Optimising Your Website for SEO',
        description: 'Tips and techniques to improve your website’s visibility on search engines.',
        link: '/knowledgebase/optimising-your-website-for-seo',
        author: 'Bob Brown',
        readTime: '7',
        date: '2023-06-10',
        category: 'SEO',
        tags: ['SEO', 'optimisation', 'marketing'],
    },
    {
        id: 5,
        title: 'Creating Backups for Your Website',
        description: 'Learn how to create and manage backups to protect your website data.',
        link: '/knowledgebase/creating-backups-for-your-website',
        author: 'Charlie Green',
        readTime: '5',
        date: '2023-06-20',
        category: 'Maintenance',
        tags: ['backup', 'data', 'maintenance'],
    },
    {
        id: 6,
        title: 'Using Analytics to Track Your Website Performance',
        description: 'An introduction to using analytics tools to monitor and improve your website’s performance.',
        link: '/knowledgebase/using-analytics-to-track-your-website-performance',
        author: 'Diana White',
        readTime: '7',
        date: '2023-06-30',
        category: 'Analytics',
        tags: ['analytics', 'performance', 'tracking'],
    },
    {
        id: 7,
        title: 'How to Install WordPress',
        description: 'A step-by-step guide to installing WordPress on your hosting account.',
        link: '/knowledgebase/how-to-install-wordpress',
        author: 'Eve Black',
        readTime: '6',
        date: '2023-07-05',
        category: 'WordPress',
        tags: ['WordPress', 'installation', 'beginner'],
    },
];